export const COLORS = {
  primary: '#E12D6E',
  solidBlack: '#000000',
  white: '#FFFFFF',
  pista: '#BBDABB',
  lightRed: '#F29B9B',
  liteWhite: '#F8F8F8',
  lightGreen: '#4CAF50',
  darkGrey: '#D1D3DC',
  lightGrey: '#E5E5E5',
  transparent: 'transparent',
  errorText: '#FF0000',
  musicCard: '#E7F4E6',
  foodCard: '#FDEAE5',
  hikingCard: '#E4F3FC',
  movieCard: '#EFEAF5',
  danceCard: '#FEF9E4',
  travelCard: '#FCF0E7',
};
